### ISSUE TITLE
Error in angular 8

### ISSUE THREAD

**Issue by AdnanSantoos** [ashish-chopra/ngx-gauge#68]
ERROR in node_modules/ngx-gauge/gauge/gauge.d.ts:24:9 - error TS1086: An accessor cannot be declared in an ambient context.

24     get size(): number;
           ~~~~
node_modules/ngx-gauge/gauge/gauge.d.ts:25:9 - error TS1086: An accessor cannot be declared in an ambient context.

25     set size(value: number);
           ~~~~
node_modules/ngx-gauge/gauge/gauge.d.ts:26:9 - error TS1086: An accessor cannot be declared in an ambient context.

26     get min(): number;
           ~~~
node_modules/ngx-gauge/gauge/gauge.d.ts:27:9 - error TS1086: An accessor cannot be declared in an ambient context.

27     set min(value: number);
           ~~~
node_modules/ngx-gauge/gauge/gauge.d.ts:28:9 - error TS1086: An accessor cannot be declared in an ambient context.

28     get animate(): boolean;
           ~~~~~~~
node_modules/ngx-gauge/gauge/gauge.d.ts:29:9 - error TS1086: An accessor cannot be declared in an ambient context.

29     set animate(value: boolean);
           ~~~~~~~
node_modules/ngx-gauge/gauge/gauge.d.ts:30:9 - error TS1086: An accessor cannot be declared in an ambient context.

30     get max(): number;
           ~~~
node_modules/ngx-gauge/gauge/gauge.d.ts:31:9 - error TS1086: An accessor cannot be declared in an ambient context.

31     set max(value: number);
           ~~~
node_modules/ngx-gauge/gauge/gauge.d.ts:42:9 - error TS1086: An accessor cannot be declared in an ambient context.

42     get value(): number;
           ~~~~~
node_modules/ngx-gauge/gauge/gauge.d.ts:43:9 - error TS1086: An accessor cannot be declared in an ambient context.

43     set value(val: number);
           ~~~~~

**Comment by ashish-chopra** [comment]
I think you are using the latest version of ngx-gauge which is upgraded to Angular 9, therefore, it is throwing error, because Angular 9 and 8 has breaking changes. Please use ngx-gauge@1.0.0-beta.12 which is for Angular 8. I will add a compatibility matrix in the README shortly. Thanks!

**Comment by AdnanSantoos** [comment]
thanks, it worked, i had used ngx-gauge@1.0.0-beta.13

**Comment by jenil777007** [comment]
@ashish-chopra, [npm package link](https://www.npmjs.com/package/ngx-gauge) mentions ngx-gauge@v1.0.0-beta.13 version as a recommended version to use in Angular 8, while beta.12 solves this problem.

**Comment by bilalsha** [comment]
Its not working on angular 8.2.14. Getting same issue
